### ISSUE TITLE
Mobile data collection based on QGIS

### ISSUE THREAD

**Issue by saberraz** [zackbatist/open-archaeo#24]
https://inputapp.io is a free and open source mobile app for Android and iOS. It is very intuitive and easy to use.
For example,  it can take geotagged photos which is very helpful for archaeologists:
https://www.lutraconsulting.co.uk/blog/2021/04/20/photo-exif-input/

**Comment by zackbatist** [comment]
This looks like a really handy tool! However I'm a bit wary of adding items that are not developed by/for archaeology specifically. Archaeologists have always used tools not specifically designed for their use cases, and the borders between what is archaeological and not archaeological are really fuzzy and/or non-existent depending on perspective. To manage scope creep, I wonder whether it might be appropriate to assign a tag called 'generic' (or some other more suitable term) to indicate tools that address broader challenges that archaeologists deal with, but which are not explicitly targeting archaeological use cases. What do you think?

I also suspect that there may be many other similar tools out there which deal with a similar or overlapping set of challenges. This might be a great topic for a deep dive (as per https://github.com/zackbatist/open-archaeo/blob/master/ToDo.md#deep-dives).

**Comment by saberraz** [comment]
This is in the same category as Collector and Qfield.
For more information see: https://github.com/lutraconsulting/input

**Comment by joeroe** [comment]
I see where you're coming from @zackbatist, but I do think mobile GIS could be an exception because it is becoming very widely used in archaeology (cf. multiple CAA sessions on it in recent years). As @saberraz says we already have QField. I can volunteer to do a "deep-dive" on this since I've written a bit about it before.

**Comment by zackbatist** [comment]
Alright, sorry for being so resistant. My first instinct is to be conservative about scope, but now I definitely see its relevance. I added this item in the most recent update.

**Comment by saberraz** [comment]
@zackbatist thanks a lot for your swift response!
