### ISSUE TITLE
Add a DOI for citing? 

### ISSUE THREAD

**Issue by benmarwick** [zackbatist/open-archaeo#29]
Would you consider creating a release and archiving it at Zenodo so this project can have a DOI? The limitation is that the DOI would reference only a snapshot of the project, but anyone going to the Zenodo page for the project would see the GitHub url and perhaps a README file that informs them that the project is ongoing and the list is growing continuously. I did this for my list of archaeology papers that include R code (https://github.com/benmarwick/ctv-archaeology/blob/master/README.md) because someone wanted to cite it. And now I'm part of a group that want to cite this project in a paper we're drafting. A DOI would make the citation more robust to any changes here at GitHub

**Comment by zackbatist** [comment]
Ok, done. I will also upload a cff file.

The zenodo record is here: https://zenodo.org/record/7666729.

Please use the concept-level doi (https://doi.org/10.5281/zenodo.7666729) instead of the version-specific doi (https://doi.org/10.5281/zenodo.7666730).

**Comment by benmarwick** [comment]
Great, thank you so much for your quick action! I've updated our manuscript with the DOI.
