### ISSUE TITLE
Interesting projects

### ISSUE THREAD

**Issue by natowi** [zackbatist/open-archaeo#8]
Data collection in the field:

Data collection in the field, works with qgis: https://qfield.org/

Archaeological Artifact Recording - Android App: https://github.com/anatolian/archaeology-object-data-collector-app

----

Reflectance Transformation Imaging:

https://custom-imaging.co.uk/software/

Website with the RTI builder (culturalheritageimaging.org) 

----

> Software (maybe a command line tool or an R package) that shows astronomical relations if given a coordinate, a coordinate and an angle, or two coordinates in eyeshot. It should allow to get a quick estimation if a certain location or man made structure was build with respect to astronomical features as discussed in Cultural Astronomy. Despite the obvious problem that correlation does not mean causation, for some contexts, like for example ritual architecture in the European Metal Ages, astronomical obervations seemed to be very relevant. This software package should allow the user to get a quick overview about possible relations like solstices, lunistice, planet rises, etc..

https://stellarium.org/
https://sites.google.com/site/stellariumuserguide/location-setting

According to Appendix F of their User Guide, a wide range of +-100000 years are supported. 
Note that Stellarium uses astronomical numeration of years - http://stellarium.sourceforge.net/wiki/index.php/FAQ#.22There_is_no_year_0.22.2C_or_.22BC_dates_are_a_year_out.22

The ArchaeoLines plugin displays any combination of declination arcs most relevant to archaeo- or ethnoastronomical studies
https://stellarium.org/doc/0.18/group__archaeoLines.html

**Comment by zackbatist** [comment]
Thank you for these suggestions! I just added them to the list, though one was already accounted for.
